add CSS env variable
felddy/foundryvtt-docker pull request #789
Opened 2023-09-21 02:19 UTC by orangepeelbeef

#  #

## 🗣 Description ##

Set an environment variable to select Setup page CSS theme

## 💭 Motivation and context ##

resolves #743 

## 🧪 Testing ##

Built the image from the develop branch, set the docker env variable and watched the CSS change

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-09-22 01:07 UTC, orangepeelbeef commented
I see that my IDE changed the format on the README.md that wasn't really intentional.  I can resubmit it without the format change, or i can let the IDE adjust the other tables as well.  Having them in different formats is probably not great.

it wants the table to look like
this
`
| Mount point | Purpose                               |
|-------------|---------------------------------------|
| `/data`     | Configuration, data, and log storage. |`
rather than this
`
| Mount point | Purpose        |
|-------------|----------------|
| `/data`    | Configuration, data, and log storage. |`


I don't think any of this is why the validation jobs are failing but let me know if you want it adjusted

2023-09-28 23:05 UTC, felddy requested changes

2023-09-28 23:05 UTC, felddy commented on README.md
Yes, Please limit your changes to the new line you are adding to the table.

2023-09-28 23:05 UTC, felddy commented on src/set_options.ts
> +  cssTheme: process.env.FOUNDRY_CSS_THEME || "foundry",
Looks good.  I thought the default should have been `null` but it is in fact `foundry`.  💪

2023-09-28 23:05 UTC, felddy commented
Sorry I've been neglecting this PR.   There was a (and still is) a big weird architecture issue that was blocking all the workflows up.   This is looking good.  See my one request to limit the README changes.

2023-09-29 00:41 UTC, felddy requested changes
Thanks for the quick update.  Just one more suggestion.

2023-09-29 00:41 UTC, felddy commented on README.md
> +| `FOUNDRY_CSS_THEME` | Choose the CSS Theme for the setup page in foundry.  Choose from foundry, fantasy, or scifi. | `foundry` |
Just a couple of formatting suggestions:

```suggestion
| `FOUNDRY_CSS_THEME` | Choose the CSS theme for the setup page.  Choose from `foundry`, `fantasy`, or `scifi`. | `foundry` |
```

2023-09-29 20:13 UTC, felddy approved these changes
Great.  Thanks.

2023-09-29 21:11 UTC, merged